id: P5B449444
initial_creation_type: input
source_metadata:
  Title: Śrīherukābhidhānaṃ Cakrasaṃvaratantram with the Vivṛti Commentary of Bhavabhaṭṭa
    [Vol II]
  Editor: Pandey, Janardan Shastri
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '2002'
  Cakrasaṃvaratantram [Vol.2]:
    Text Version: Romanized
    Input Personnel: Milan Shakya
    Input Date: '2013'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of the Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:13:56.942792'
last_modified_at: '2022-03-08T16:13:56.942803'
